version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "yearly"

  # The npm dependencies are updated yearly instead of monthly to reduce noise from frequent updates.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "yearly"
