[editor]
command = "code"

[create]
auto_editor_open = false
auto_git_add = false
clipboard_message = "Create: ${url}"

[judge]
clipboard_message = "AC: ${url} ${lang}"

[language]
default = "python3"

[language.settings.cpp]
source_file_name = "main.cpp"
template_file = "templates/main.cpp"
[language.settings.cpp.commands]
pre_execute = [
    "g++ --version",
    "g++ ${source_file} -o ${dir}/a.out",
]
execute = "${dir}/a.out"

[language.settings.python3]
source_file_name = "main.py"
template_file = "templates/main.py"
[language.settings.python3.commands]
pre_execute = ["python3 --version"]
execute = "python3 ${source_file}"
