[editor]
command = "code"

[create]
auto_editor_open = false
auto_git_add = false
clipboard_message = "Create: ${url}"

[judge]
clipboard_message = "AC: ${url} ${lang}"

[language]
default = "pypy3"

[language.settings.cpp]
source_file_name = "main.cpp"
template_file = "templates/main.cpp"
[language.settings.cpp.commands]
pre_execute = [
    "g++ --version",
    "g++ ${source_file} -o ${dir}/a.out",
]
execute = "${dir}/a.out"

[language.settings.pypy3]
source_file_name = "main.py"
template_file = "templates/main.py"
[language.settings.pypy3.commands]
pre_execute = ["pypy3 --version"]
execute = "pypy3 ${source_file}"

[language.settings.python3]
source_file_name = "main.py"
template_file = "templates/main.py"
[language.settings.python3.commands]
pre_execute = ["python3 --version"]
execute = "python3 ${source_file}"

[language.settings.ts]
source_file_name = "main.ts"
template_file = "templates/main.ts"
[language.settings.ts.commands]
pre_execute = [
    "tsc --version",
    "tsc --target ESNEXT --module commonjs ${source_file}",
]
execute = "node ${dir}/main.js"
